### ISSUE TITLE
[ERROR] when rendering GdmlCone and GdmlTrapezoid (Jupyter)

### ISSUE THREAD

**Issue by lobis** [mipt-npm/visionforge#39]
I found an error when rendering a geometry containing a `GdmlCone`. The geometry seems to work fine otherwise though, I have exported it to GDML and visualized to check that every volume looks alright (including the cones), so I guess it must be a rendering issue.

Edit: I think they are just not implemented yet, since it also happens with other non trivial solids. For my use case I would need to render `GdmlCone` and `GdmlTrapezoid` at least. Thanks!

A Jupyter notebook that can be used to reproduce this problem can be found at [https://lfna.unizar.es/iaxo/iaxo-geometry/-/blob/fe74c0460c361974f6407b25590ed49aa6f4b55e/gdml.kt/gdml.kt.ipynb](url) (needs LFNA / University of Zaragoza access).

The error is the following:
```
[ERROR] 
org.jetbrains.kotlinx.jupyter.compiler.util.ReplLibraryException: The problem is found in one of the loaded libraries: check library renderers
	at org.jetbrains.kotlinx.jupyter.compiler.util.ExceptionsKt.rethrowAsLibraryException(exceptions.kt:65)
	at org.jetbrains.kotlinx.jupyter.codegen.TypeRenderersProcessorImpl.renderResult(TypeRenderersProcessorImpl.kt:23)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$eval$1$$special$$inlined$let$lambda$1.invoke(repl.kt:365)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll(logging.kt:24)
	at org.jetbrains.kotlinx.jupyter.config.LoggingKt.catchAll$default(logging.kt:23)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$eval$1.invoke(repl.kt:364)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$eval$1.invoke(repl.kt:144)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.withEvalContext(repl.kt:335)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.eval(repl.kt:350)
	at org.jetbrains.kotlinx.jupyter.ProtocolKt$shellMessagesHandler$res$1.invoke(protocol.kt:287)
	at org.jetbrains.kotlinx.jupyter.ProtocolKt$shellMessagesHandler$res$1.invoke(protocol.kt)
	at org.jetbrains.kotlinx.jupyter.ProtocolKt.evalWithIO(protocol.kt:443)
	at org.jetbrains.kotlinx.jupyter.ProtocolKt.shellMessagesHandler(protocol.kt:286)
	at org.jetbrains.kotlinx.jupyter.IkotlinKt.kernelServer(ikotlin.kt:133)
	at org.jetbrains.kotlinx.jupyter.IkotlinKt.kernelServer$default(ikotlin.kt:101)
	at org.jetbrains.kotlinx.jupyter.IkotlinKt.main(ikotlin.kt:74)
Caused by: java.lang.IllegalArgumentException: Empty cones are not supported
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid(GdmlTransformer.kt:173)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid$default(GdmlTransformer.kt:154)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid(GdmlTransformer.kt:242)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid$default(GdmlTransformer.kt:154)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid(GdmlTransformer.kt:236)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid$default(GdmlTransformer.kt:154)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid(GdmlTransformer.kt:236)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid$default(GdmlTransformer.kt:154)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid(GdmlTransformer.kt:236)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid$default(GdmlTransformer.kt:154)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid(GdmlTransformer.kt:236)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid$default(GdmlTransformer.kt:154)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolid(GdmlTransformer.kt:242)
	at space.kscience.visionforge.gdml.GdmlTransformer.proxySolid(GdmlTransformer.kt:67)
	at space.kscience.visionforge.gdml.GdmlTransformer.addSolidWithCaching(GdmlTransformer.kt:272)
	at space.kscience.visionforge.gdml.GdmlTransformer.addPhysicalVolume(GdmlTransformer.kt:292)
	at space.kscience.visionforge.gdml.GdmlTransformer.volume(GdmlTransformer.kt:343)
	at space.kscience.visionforge.gdml.GdmlTransformer.transform(GdmlTransformer.kt:381)
	at space.kscience.visionforge.gdml.GdmlTransformerKt.toVision(GdmlTransformer.kt:387)
	at space.kscience.visionforge.gdml.GdmlTransformerKt.toVision$default(GdmlTransformer.kt:385)
	at space.kscience.visionforge.gdml.jupyter.GdmlForJupyter$onLoaded$3$fragment$1.invoke(GdmlForJupyter.kt:71)
	at space.kscience.visionforge.gdml.jupyter.GdmlForJupyter$onLoaded$3$fragment$1.invoke(GdmlForJupyter.kt:70)
	at space.kscience.visionforge.html.StaticHtmlRenderKt.embedVisionFragment(staticHtmlRender.kt:28)
	at space.kscience.visionforge.html.StaticHtmlRenderKt.embedVisionFragment(staticHtmlRender.kt:36)
	at space.kscience.visionforge.html.StaticHtmlRenderKt.embedVisionFragment$default(staticHtmlRender.kt:32)
	at space.kscience.visionforge.gdml.jupyter.GdmlForJupyter.produceHtmlVisionString(GdmlForJupyter.kt:35)
	at space.kscience.visionforge.gdml.jupyter.GdmlForJupyter.access$produceHtmlVisionString(GdmlForJupyter.kt:25)
	at space.kscience.visionforge.gdml.jupyter.GdmlForJupyter$onLoaded$3.invoke(GdmlForJupyter.kt:73)
	at space.kscience.visionforge.gdml.jupyter.GdmlForJupyter$onLoaded$3.invoke(GdmlForJupyter.kt:69)
	at space.kscience.visionforge.gdml.jupyter.GdmlForJupyter$onLoaded$$inlined$render$1.execute(JupyterIntegration.kt:77)
	at org.jetbrains.kotlinx.jupyter.codegen.TypeRenderersProcessorImpl$renderResult$newField$1.invoke(TypeRenderersProcessorImpl.kt:24)
	at org.jetbrains.kotlinx.jupyter.codegen.TypeRenderersProcessorImpl$renderResult$newField$1.invoke(TypeRenderersProcessorImpl.kt:12)
	at org.jetbrains.kotlinx.jupyter.compiler.util.ExceptionsKt.rethrowAsLibraryException(exceptions.kt:63)
	... 15 more
```

**Comment by altavir** [comment]
Reproduced the problem. I just did not implement converters for cone surfaces. Will do that right away.
