### ISSUE TITLE
Compatibility problems when exporting to vision with newest gdml.kt version

### ISSUE THREAD

**Issue by lobis** [mipt-npm/visionforge#40]
I get an error when trying to obtain the json encoding of the geometry when using the latest gdml.kt version, which is probably due to a compatibility problem (perhaps this issue belongs on that repo instead).

```
val gdmlString: String =
    File("C:\\WSL-Ubuntu-20.04\\github\\gdml\\src\\main\\resources\\cubes.gdml").readText(Charsets.UTF_8)

val cubes = Gdml.decodeFromString(gdmlString)

val vision = cubes.toVision {}

val json = Solids.encodeToString(vision)
println(json)
```

This piece of code gives the following error when ran with visionforge version `0.2.0-dev-13` and gdml.kt version `0.4.0-dev-3`:

```
> Task :run FAILED
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: 'space.kscience.gdml.GdmlGroup space.kscience.gdml.Gdml.getWorld()'
	at space.kscience.visionforge.gdml.GdmlTransformer.transform(GdmlTransformer.kt:381)
	at space.kscience.visionforge.gdml.GdmlTransformerKt.toVision(GdmlTransformer.kt:387)
	at MainKt$main$1.invoke(main.kt:791)
	at MainKt$main$1.invoke(main.kt)
	at space.kscience.visionforge.VisionForgeJvmKt.invoke(visionForgeJvm.kt:20)
	at MainKt.main(main.kt:784)
	at MainKt.main(main.kt)

Execution failed for task ':run'.
> Process 'command 'C:\Users\lobis\.jdks\corretto-11.0.10\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

However if I downgrade to gdml.kt version `0.3.0` it works without an issue.

Looks like some method changed name perhaps?

**Comment by altavir** [comment]
Yes, versions are incompatible. I will release new versions of everything soon.
